Layout Builder Compatibility
YCloudYUSA/yusaopeny_gated_content pull request #29
Opened 2023-03-09 15:52 UTC by Sardis93

Check not only for Paragraph but Block during Virtual Y Login Rediret, ensuring compatibility with Layout Builder.

**Related Issue/Ticket:**

**PLEASE CHECK BASE BRANCH FOR YOUR PR**
**ONLY urgent and approved fixes for point release should go to master branch**

(Replace this line with a link to the related GitHub issue on [YCloudYUSA/yusaopeny_gated_content](https://github.com/YCloudYUSA/yusaopeny_gated_content/issues) or your own ticketing system)

## Steps to test:

- [ ] Enable Layout Builder module.
- [ ] Enable openy_gc_auth_example module.
- [ ] Create Content Type for Layout Builder.
- [ ] Create node and add **Virtual Y Content** Block via Layout Builder.
- [ ] Create another node with **Virtual Y Content Login** Block via Layout Builder. 
- [ ] Set up **Virtual Y Landing Page url** and **Virtual Y Login Landing Page url** fields on settings page: _admin/openy/virtual-ymca_
- [ ] Navigate to the page with **Virtual Y Content Login** block and hit **Enter Virtual Y** button.
- [ ] Observe redirect to the node with **Virtual Y Content** Block
 
## Quality checks:

Please check these boxes to confirm this PR covers the following cases:

- Maintaining our upgrade path is essential. Check one or the other:
  - [x] This PR  provides updates via `hook_update_N` or other means.
- Front end fixes should be tested against all of the Open Y Themes.
  - [ ] Tested against Carnation
  - [ ] Tested against Lily
  - [ ] Tested against Rose
  - [x] This change does not contain front-end fixes.
- [x] I have flagged this PR "Needs Review" or pinged the VY devs/QA
  team in Slack

2023-03-09 16:20 UTC, anpolimus commented on config/install/block_content.type.gated_content_login.yml
> +description: 'A block to display Virtual Y Content login paragraph.'
```suggestion
description: 'A block to display Virtual Y Content login.'
```

2023-03-09 16:23 UTC, anpolimus requested changes
Thanks for your approach, but this requests needs to be changed.
We are trying to get rid of paragraphs in the future.
This means that having a paragraph inside the block is not the way how we want to render VY in the future.
We need a simple custom block that renders an app inside it's template.
It will make your check code a little bit complex but module will be less dependant on paragraphs.

2023-04-09 16:49 UTC, anpolimus requested changes
@Sardis93 in this project we try to create a new block for each widget since we want to have a base for future improvements and comfortable use on the LB custom block level.
Please, return VY block back.

2023-04-10 14:56 UTC, anpolimus approved these changes

2023-04-19 09:51 UTC, podarok requested changes
Small thing to get merged

2023-04-19 09:51 UTC, podarok commented on src/Plugin/Block/VirtualYApp.php
> +    $this->moduleHandler->alter('virtual_y_app_settings', $app_config);
Let's have this documented in modulename.api.php file, please

2023-04-19 14:47 UTC, Sardis93 commented
Hey, @podarok !

The alter hook you suggest to document is not a new hook i added, it's the one we used from before and it is already in the api.php file. Please, see the link:

https://github.com/YCloudYUSA/yusaopeny_gated_content/blob/master/openy_gated_content.api.php#L22

2023-04-19 16:03 UTC, merged